services:
  - type: web
    name: url-analyzer-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0